service: call-api-lambda
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-1

functions:
  app:
    handler: index.handler
    events:
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true

